// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: GenerateLexical.jflex

/*

Grupo

Nome: André Dias Nunes
Matrícula: 201665570C

Nome: Guilherme Barbosa
Matrícula: 201435031

*/


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexical {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int SINGLELINECOMMENT = 2;
  public static final int MULTLINECOMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u1f00\1\u3500\1\u3600\1\u3700\1\u3800\1\u0100"+
    "\1\u3900\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u1f00"+
    "\1\u4000\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u1f00\1\u4c00\1\u4d00\1\u4e00"+
    "\1\u1f00\3\u0100\1\u4f00\1\u5000\1\u5100\12\u1f00\4\u0100\1\u5200"+
    "\17\u1f00\2\u0100\1\u5300\41\u1f00\2\u0100\1\u5400\1\u5500\2\u1f00"+
    "\1\u5600\1\u5700\27\u0100\1\u5800\2\u0100\1\u5900\45\u1f00\1\u0100"+
    "\1\u5a00\1\u5b00\11\u1f00\1\u5c00\27\u1f00\1\u5d00\1\u5e00\1\u5f00"+
    "\1\u6000\11\u1f00\1\u6100\1\u6200\5\u1f00\1\u6300\1\u6400\4\u1f00"+
    "\1\u6500\21\u1f00\246\u0100\1\u6600\20\u0100\1\u6700\1\u6800\25\u0100"+
    "\1\u6900\34\u0100\1\u6a00\14\u1f00\2\u0100\1\u6b00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\3\0\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\12\20\1\21\1\22"+
    "\1\23\1\24\1\25\2\0\1\26\1\27\1\30\2\26"+
    "\1\31\2\26\1\32\21\26\1\33\1\34\1\35\1\0"+
    "\1\36\1\0\1\37\1\40\1\26\1\41\1\42\1\43"+
    "\1\26\1\44\1\45\2\26\1\46\1\26\1\47\1\50"+
    "\1\51\1\26\1\52\1\53\1\54\1\55\1\26\1\56"+
    "\3\26\1\57\1\0\1\60\54\0\1\26\12\0\1\26"+
    "\4\0\1\26\5\0\27\26\1\0\37\26\1\0\u01ca\26"+
    "\4\0\14\26\16\0\5\26\7\0\1\26\1\0\1\26"+
    "\201\0\5\26\1\0\2\26\2\0\4\26\1\0\1\26"+
    "\6\0\1\26\1\0\3\26\1\0\1\26\1\0\24\26"+
    "\1\0\123\26\1\0\213\26\10\0\246\26\1\0\46\26"+
    "\2\0\1\26\6\0\51\26\107\0\33\26\4\0\4\26"+
    "\55\0\53\26\25\0\12\20\4\0\2\26\1\0\143\26"+
    "\1\0\1\26\17\0\2\26\7\0\2\26\12\20\3\26"+
    "\2\0\1\26\20\0\1\26\1\0\36\26\35\0\131\26"+
    "\13\0\1\26\16\0\12\20\41\26\11\0\2\26\4\0"+
    "\1\26\5\0\26\26\4\0\1\26\11\0\1\26\3\0"+
    "\1\26\27\0\31\26\7\0\13\26\65\0\25\26\1\0"+
    "\10\26\106\0\66\26\3\0\1\26\22\0\1\26\7\0"+
    "\12\26\4\0\12\20\1\0\20\26\4\0\10\26\2\0"+
    "\2\26\2\0\26\26\1\0\7\26\1\0\1\26\3\0"+
    "\4\26\3\0\1\26\20\0\1\26\15\0\2\26\1\0"+
    "\3\26\4\0\12\20\2\26\12\0\1\26\10\0\6\26"+
    "\4\0\2\26\2\0\26\26\1\0\7\26\1\0\2\26"+
    "\1\0\2\26\1\0\2\26\37\0\4\26\1\0\1\26"+
    "\7\0\12\20\2\0\3\26\20\0\11\26\1\0\3\26"+
    "\1\0\26\26\1\0\7\26\1\0\2\26\1\0\5\26"+
    "\3\0\1\26\22\0\1\26\17\0\2\26\4\0\12\20"+
    "\11\0\1\26\13\0\10\26\2\0\2\26\2\0\26\26"+
    "\1\0\7\26\1\0\2\26\1\0\5\26\3\0\1\26"+
    "\36\0\2\26\1\0\3\26\4\0\12\20\1\0\1\26"+
    "\21\0\1\26\1\0\6\26\3\0\3\26\1\0\4\26"+
    "\3\0\2\26\1\0\1\26\1\0\2\26\3\0\2\26"+
    "\3\0\3\26\3\0\14\26\26\0\1\26\25\0\12\20"+
    "\25\0\10\26\1\0\3\26\1\0\27\26\1\0\20\26"+
    "\3\0\1\26\32\0\3\26\5\0\2\26\4\0\12\20"+
    "\20\0\1\26\4\0\10\26\1\0\3\26\1\0\27\26"+
    "\1\0\12\26\1\0\5\26\3\0\1\26\40\0\1\26"+
    "\1\0\2\26\4\0\12\20\1\0\2\26\22\0\10\26"+
    "\1\0\3\26\1\0\51\26\2\0\1\26\20\0\1\26"+
    "\5\0\3\26\10\0\3\26\4\0\12\20\12\0\6\26"+
    "\5\0\22\26\3\0\30\26\1\0\11\26\1\0\1\26"+
    "\2\0\7\26\37\0\12\20\21\0\60\26\1\0\2\26"+
    "\14\0\7\26\11\0\12\20\47\0\2\26\1\0\1\26"+
    "\1\0\5\26\1\0\30\26\1\0\1\26\1\0\12\26"+
    "\1\0\2\26\11\0\1\26\2\0\5\26\1\0\1\26"+
    "\11\0\12\20\2\0\4\26\40\0\1\26\37\0\12\20"+
    "\26\0\10\26\1\0\44\26\33\0\5\26\163\0\53\26"+
    "\24\0\1\26\12\20\6\0\6\26\4\0\4\26\3\0"+
    "\1\26\3\0\2\26\7\0\3\26\4\0\15\26\14\0"+
    "\1\26\1\0\12\20\6\0\46\26\1\0\1\26\5\0"+
    "\1\26\2\0\53\26\1\0\115\26\1\0\4\26\2\0"+
    "\7\26\1\0\1\26\1\0\4\26\2\0\51\26\1\0"+
    "\4\26\2\0\41\26\1\0\4\26\2\0\7\26\1\0"+
    "\1\26\1\0\4\26\2\0\17\26\1\0\71\26\1\0"+
    "\4\26\2\0\103\26\45\0\20\26\20\0\126\26\2\0"+
    "\6\26\3\0\u016c\26\2\0\21\26\1\0\32\26\5\0"+
    "\113\26\6\0\10\26\7\0\15\26\1\0\4\26\16\0"+
    "\22\26\16\0\22\26\16\0\15\26\1\0\3\26\17\0"+
    "\64\26\43\0\1\26\4\0\1\26\3\0\12\20\46\0"+
    "\12\20\6\0\131\26\7\0\5\26\2\0\42\26\1\0"+
    "\1\26\5\0\106\26\12\0\37\26\47\0\12\20\36\26"+
    "\2\0\5\26\13\0\54\26\4\0\32\26\6\0\12\20"+
    "\46\0\27\26\11\0\65\26\53\0\12\20\6\0\12\20"+
    "\15\0\1\26\135\0\57\26\21\0\7\26\4\0\12\20"+
    "\51\0\36\26\15\0\2\26\12\20\54\26\32\0\44\26"+
    "\34\0\12\20\3\0\3\26\12\20\44\26\2\0\11\26"+
    "\7\0\53\26\2\0\3\26\51\0\4\26\1\0\6\26"+
    "\1\0\2\26\3\0\1\26\5\0\300\26\100\0\26\26"+
    "\2\0\6\26\2\0\46\26\2\0\6\26\2\0\10\26"+
    "\1\0\1\26\1\0\1\26\1\0\1\26\1\0\37\26"+
    "\2\0\65\26\1\0\7\26\1\0\1\26\3\0\3\26"+
    "\1\0\7\26\3\0\4\26\2\0\6\26\4\0\15\26"+
    "\5\0\3\26\1\0\7\26\164\0\1\26\15\0\1\26"+
    "\20\0\15\26\145\0\1\26\4\0\1\26\2\0\12\26"+
    "\1\0\1\26\3\0\5\26\6\0\1\26\1\0\1\26"+
    "\1\0\1\26\1\0\4\26\1\0\13\26\2\0\4\26"+
    "\5\0\5\26\4\0\1\26\64\0\2\26\u017b\0\57\26"+
    "\1\0\57\26\1\0\205\26\6\0\4\26\3\0\2\26"+
    "\14\0\46\26\1\0\1\26\5\0\1\26\2\0\70\26"+
    "\7\0\1\26\20\0\27\26\11\0\7\26\1\0\7\26"+
    "\1\0\7\26\1\0\7\26\1\0\7\26\1\0\7\26"+
    "\1\0\7\26\1\0\7\26\120\0\1\26\325\0\2\26"+
    "\52\0\5\26\5\0\2\26\4\0\126\26\6\0\3\26"+
    "\1\0\132\26\1\0\4\26\5\0\53\26\1\0\136\26"+
    "\21\0\33\26\65\0\306\26\112\0\360\26\20\0\215\26"+
    "\103\0\56\26\2\0\15\26\3\0\20\26\12\20\2\26"+
    "\24\0\57\26\20\0\37\26\2\0\106\26\61\0\11\26"+
    "\2\0\147\26\2\0\65\26\2\0\5\26\60\0\13\26"+
    "\1\0\3\26\1\0\4\26\1\0\27\26\35\0\64\26"+
    "\16\0\62\26\34\0\12\20\30\0\6\26\3\0\1\26"+
    "\1\0\2\26\1\0\12\20\34\26\12\0\27\26\31\0"+
    "\35\26\7\0\57\26\34\0\1\26\12\20\6\0\5\26"+
    "\1\0\12\26\12\20\5\26\1\0\51\26\27\0\3\26"+
    "\1\0\10\26\4\0\12\20\6\0\27\26\3\0\1\26"+
    "\3\0\62\26\1\0\1\26\3\0\2\26\2\0\5\26"+
    "\2\0\1\26\1\0\1\26\30\0\3\26\2\0\13\26"+
    "\7\0\3\26\14\0\6\26\2\0\6\26\2\0\6\26"+
    "\11\0\7\26\1\0\7\26\1\0\53\26\1\0\14\26"+
    "\10\0\163\26\15\0\12\20\6\0\244\26\14\0\27\26"+
    "\4\0\61\26\4\0\156\26\2\0\152\26\46\0\7\26"+
    "\14\0\5\26\5\0\1\26\1\0\12\26\1\0\15\26"+
    "\1\0\5\26\1\0\1\26\1\0\2\26\1\0\2\26"+
    "\1\0\154\26\41\0\153\26\22\0\100\26\2\0\66\26"+
    "\50\0\14\26\164\0\5\26\1\0\207\26\23\0\12\20"+
    "\7\0\32\26\6\0\32\26\13\0\131\26\3\0\6\26"+
    "\2\0\6\26\2\0\6\26\2\0\3\26\43\0\14\26"+
    "\1\0\32\26\1\0\23\26\1\0\2\26\1\0\17\26"+
    "\2\0\16\26\42\0\173\26\205\0\35\26\3\0\61\26"+
    "\57\0\40\26\15\0\24\26\1\0\10\26\6\0\46\26"+
    "\12\0\36\26\2\0\44\26\4\0\10\26\60\0\236\26"+
    "\2\0\12\20\6\0\44\26\4\0\44\26\4\0\50\26"+
    "\10\0\64\26\234\0\67\26\11\0\26\26\12\0\10\26"+
    "\230\0\6\26\2\0\1\26\1\0\54\26\1\0\2\26"+
    "\3\0\1\26\2\0\27\26\12\0\27\26\11\0\37\26"+
    "\101\0\23\26\1\0\2\26\12\0\26\26\12\0\32\26"+
    "\106\0\70\26\6\0\2\26\100\0\1\26\17\0\4\26"+
    "\1\0\3\26\1\0\35\26\52\0\35\26\3\0\35\26"+
    "\43\0\10\26\1\0\34\26\33\0\66\26\12\0\26\26"+
    "\12\0\23\26\15\0\22\26\156\0\111\26\67\0\63\26"+
    "\15\0\63\26\15\0\44\26\14\0\12\20\306\0\35\26"+
    "\12\0\1\26\10\0\26\26\232\0\27\26\14\0\65\26"+
    "\56\0\12\20\23\0\55\26\40\0\31\26\7\0\12\20"+
    "\11\0\44\26\17\0\12\20\4\0\1\26\13\0\43\26"+
    "\3\0\1\26\14\0\60\26\16\0\4\26\13\0\12\20"+
    "\1\26\1\0\1\26\43\0\22\26\1\0\31\26\124\0"+
    "\7\26\1\0\1\26\1\0\4\26\1\0\17\26\1\0"+
    "\12\26\7\0\57\26\21\0\12\20\13\0\10\26\2\0"+
    "\2\26\2\0\26\26\1\0\7\26\1\0\2\26\1\0"+
    "\5\26\3\0\1\26\22\0\1\26\14\0\5\26\236\0"+
    "\65\26\22\0\4\26\5\0\12\20\5\0\1\26\40\0"+
    "\60\26\24\0\2\26\1\0\1\26\10\0\12\20\246\0"+
    "\57\26\51\0\4\26\44\0\60\26\24\0\1\26\13\0"+
    "\12\20\46\0\53\26\15\0\1\26\7\0\12\20\66\0"+
    "\33\26\25\0\12\20\306\0\54\26\164\0\100\26\12\20"+
    "\25\0\1\26\240\0\10\26\2\0\47\26\20\0\1\26"+
    "\1\0\1\26\34\0\1\26\12\0\50\26\7\0\1\26"+
    "\25\0\1\26\13\0\56\26\23\0\1\26\42\0\71\26"+
    "\7\0\11\26\1\0\45\26\21\0\1\26\17\0\12\20"+
    "\30\0\36\26\160\0\7\26\1\0\2\26\1\0\46\26"+
    "\25\0\1\26\11\0\12\20\6\0\6\26\1\0\2\26"+
    "\1\0\40\26\16\0\1\26\7\0\12\20\u0136\0\23\26"+
    "\15\0\232\26\346\0\304\26\274\0\57\26\321\0\107\26"+
    "\271\0\71\26\7\0\37\26\1\0\12\20\146\0\36\26"+
    "\22\0\60\26\20\0\4\26\14\0\12\20\11\0\25\26"+
    "\5\0\23\26\260\0\100\26\200\0\113\26\5\0\1\26"+
    "\102\0\15\26\100\0\2\26\1\0\1\26\34\0\370\26"+
    "\10\0\363\26\15\0\37\26\61\0\3\26\21\0\4\26"+
    "\10\0\u018c\26\4\0\153\26\5\0\15\26\3\0\11\26"+
    "\7\0\12\26\146\0\125\26\1\0\107\26\1\0\2\26"+
    "\2\0\1\26\2\0\2\26\2\0\4\26\1\0\14\26"+
    "\1\0\1\26\1\0\7\26\1\0\101\26\1\0\4\26"+
    "\2\0\10\26\1\0\7\26\1\0\34\26\1\0\4\26"+
    "\1\0\5\26\1\0\1\26\3\0\7\26\1\0\u0154\26"+
    "\2\0\31\26\1\0\31\26\1\0\37\26\1\0\31\26"+
    "\1\0\37\26\1\0\31\26\1\0\37\26\1\0\31\26"+
    "\1\0\37\26\1\0\31\26\1\0\10\26\2\0\62\20"+
    "\55\26\12\0\7\26\2\0\12\20\4\0\1\26\u0171\0"+
    "\54\26\4\0\12\20\6\0\305\26\73\0\104\26\7\0"+
    "\1\26\4\0\12\20\246\0\4\26\1\0\33\26\1\0"+
    "\2\26\1\0\1\26\2\0\1\26\1\0\12\26\1\0"+
    "\4\26\1\0\1\26\1\0\1\26\6\0\1\26\4\0"+
    "\1\26\1\0\1\26\1\0\1\26\1\0\3\26\1\0"+
    "\2\26\1\0\1\26\2\0\1\26\1\0\1\26\1\0"+
    "\1\26\1\0\1\26\1\0\1\26\1\0\2\26\1\0"+
    "\1\26\2\0\4\26\1\0\7\26\1\0\4\26\1\0"+
    "\4\26\1\0\1\26\1\0\12\26\1\0\21\26\5\0"+
    "\3\26\1\0\5\26\1\0\21\26\104\0\327\26\51\0"+
    "\65\26\13\0\336\26\2\0\u0182\26\16\0\u0131\26\37\0"+
    "\36\26\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27648];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\5\23\1\24\1\25\7\23"+
    "\1\26\1\27\2\30\1\2\1\31\1\32\1\0\1\33"+
    "\2\0\1\34\1\0\1\35\1\36\1\37\6\23\1\40"+
    "\6\23\1\41\1\33\3\23\1\42\3\23\1\43\5\23"+
    "\1\44\1\45\1\23\1\46\2\23\1\47\1\23\1\50"+
    "\1\23\1\51\1\52\1\53\1\23\1\54\2\23\1\55"+
    "\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\223\0\304\0\365\0\223"+
    "\0\u0126\0\u0157\0\223\0\223\0\223\0\223\0\223\0\u0188"+
    "\0\u01b9\0\223\0\u01ea\0\u021b\0\223\0\223\0\u024c\0\223"+
    "\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\223\0\223\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\223"+
    "\0\223\0\u04fa\0\u052b\0\223\0\223\0\u055c\0\u058d\0\u05be"+
    "\0\u05ef\0\223\0\u01b9\0\u0620\0\223\0\223\0\u0651\0\u0682"+
    "\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u027d\0\u0777\0\u07a8\0\u07d9"+
    "\0\u080a\0\u083b\0\u086c\0\223\0\223\0\u089d\0\u08ce\0\u08ff"+
    "\0\u027d\0\u0930\0\u0961\0\u0992\0\u027d\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u0a56\0\u0a87\0\u027d\0\u027d\0\u0ab8\0\u027d\0\u0ae9\0\u0b1a"+
    "\0\u027d\0\u0b4b\0\u027d\0\u0b7c\0\u027d\0\u027d\0\u027d\0\u0bad"+
    "\0\u027d\0\u0bde\0\u0c0f\0\u027d\0\u027d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\4\1\37\1\4\3\31\1\40"+
    "\1\41\1\31\1\42\1\31\1\43\1\31\1\44\1\45"+
    "\1\31\1\46\2\31\1\47\1\50\2\5\1\51\1\52"+
    "\72\5\1\53\43\5\63\0\1\5\102\0\1\54\42\0"+
    "\1\55\52\0\7\56\1\57\16\56\5\60\1\56\1\61"+
    "\2\56\20\60\2\56\15\0\1\62\61\0\1\63\1\0"+
    "\1\64\56\0\1\63\1\0\1\23\61\0\1\65\63\0"+
    "\1\66\54\0\1\31\5\0\5\31\3\0\21\31\22\0"+
    "\1\31\5\0\5\31\3\0\12\31\1\67\6\31\22\0"+
    "\1\31\5\0\5\31\3\0\6\31\1\70\12\31\22\0"+
    "\1\31\5\0\5\31\3\0\10\31\1\71\10\31\22\0"+
    "\1\31\5\0\5\31\3\0\11\31\1\72\7\31\22\0"+
    "\1\31\5\0\5\31\3\0\10\31\1\73\10\31\22\0"+
    "\1\31\5\0\5\31\3\0\1\31\1\74\17\31\22\0"+
    "\1\31\5\0\5\31\3\0\5\31\1\75\10\31\1\76"+
    "\2\31\22\0\1\31\5\0\5\31\3\0\4\31\1\77"+
    "\12\31\1\100\1\31\22\0\1\31\5\0\5\31\3\0"+
    "\14\31\1\101\4\31\22\0\1\31\5\0\5\31\3\0"+
    "\4\31\1\102\14\31\22\0\1\31\5\0\5\31\3\0"+
    "\14\31\1\103\4\31\17\0\1\104\45\0\1\51\136\0"+
    "\1\51\7\0\1\105\60\0\1\57\16\0\5\60\4\0"+
    "\20\60\11\0\1\105\16\0\5\60\4\0\20\60\11\0"+
    "\1\56\24\0\1\56\3\0\1\56\6\0\1\56\2\0"+
    "\1\56\1\0\1\56\24\0\1\64\60\0\1\31\5\0"+
    "\5\31\3\0\12\31\1\106\6\31\22\0\1\31\5\0"+
    "\5\31\3\0\1\31\1\107\17\31\22\0\1\31\5\0"+
    "\5\31\3\0\12\31\1\110\6\31\22\0\1\31\5\0"+
    "\5\31\3\0\16\31\1\111\2\31\22\0\1\31\5\0"+
    "\5\31\3\0\15\31\1\112\3\31\22\0\1\31\5\0"+
    "\5\31\3\0\10\31\1\113\10\31\22\0\1\31\5\0"+
    "\5\31\3\0\4\31\1\114\14\31\22\0\1\31\5\0"+
    "\5\31\3\0\20\31\1\115\22\0\1\31\5\0\5\31"+
    "\3\0\10\31\1\116\10\31\22\0\1\31\5\0\5\31"+
    "\3\0\7\31\1\117\11\31\22\0\1\31\5\0\5\31"+
    "\3\0\1\31\1\120\14\31\1\121\2\31\22\0\1\31"+
    "\5\0\5\31\3\0\17\31\1\122\1\31\22\0\1\31"+
    "\5\0\5\31\3\0\10\31\1\123\10\31\22\0\1\31"+
    "\5\0\5\31\3\0\14\31\1\124\4\31\22\0\1\31"+
    "\5\0\5\31\3\0\1\31\1\125\17\31\22\0\1\31"+
    "\5\0\5\31\3\0\4\31\1\126\14\31\22\0\1\31"+
    "\5\0\5\31\3\0\15\31\1\127\3\31\22\0\1\31"+
    "\5\0\5\31\3\0\14\31\1\130\4\31\22\0\1\31"+
    "\5\0\5\31\3\0\10\31\1\131\10\31\22\0\1\31"+
    "\5\0\5\31\3\0\11\31\1\132\7\31\22\0\1\31"+
    "\5\0\5\31\3\0\3\31\1\133\15\31\22\0\1\31"+
    "\5\0\5\31\3\0\17\31\1\134\1\31\22\0\1\31"+
    "\5\0\5\31\3\0\4\31\1\135\14\31\22\0\1\31"+
    "\5\0\5\31\3\0\16\31\1\136\2\31\22\0\1\31"+
    "\5\0\5\31\3\0\4\31\1\137\14\31\22\0\1\31"+
    "\5\0\5\31\3\0\1\31\1\140\17\31\22\0\1\31"+
    "\5\0\5\31\3\0\16\31\1\141\2\31\22\0\1\31"+
    "\5\0\5\31\3\0\14\31\1\142\4\31\22\0\1\31"+
    "\5\0\5\31\3\0\16\31\1\143\2\31\22\0\1\31"+
    "\5\0\5\31\3\0\11\31\1\144\7\31\22\0\1\31"+
    "\5\0\5\31\3\0\4\31\1\145\14\31\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3136];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\2\1\1\11\2\1\5\11\2\1\1\11"+
    "\2\1\2\11\1\1\1\11\5\1\2\11\10\1\2\11"+
    "\2\1\2\11\1\0\1\1\2\0\1\11\1\0\1\1"+
    "\2\11\15\1\2\11\40\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token symbol (TokenType type) {
        return new Token (type, yytext(), yyline+1, yycolumn+1);
    }

    private Token symbol (TokenType type, Object value) {
        return new Token (type, value, yyline+1, yycolumn+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexical(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character: " + yytext());
            }
            // fall through
          case 47: break;
          case 2:
            { /* Não faz nada */
            }
            // fall through
          case 48: break;
          case 3:
            { return symbol(TokenType.NOT);
            }
            // fall through
          case 49: break;
          case 4:
            { return symbol(TokenType.MOD);
            }
            // fall through
          case 50: break;
          case 5:
            { return symbol(TokenType.LEFTPARENT);
            }
            // fall through
          case 51: break;
          case 6:
            { return symbol(TokenType.RIGHTPARENT);
            }
            // fall through
          case 52: break;
          case 7:
            { return symbol(TokenType.MULT);
            }
            // fall through
          case 53: break;
          case 8:
            { return symbol(TokenType.PLUS);
            }
            // fall through
          case 54: break;
          case 9:
            { return symbol(TokenType.COMMA);
            }
            // fall through
          case 55: break;
          case 10:
            { return symbol(TokenType.MINUS);
            }
            // fall through
          case 56: break;
          case 11:
            { return symbol(TokenType.DOT);
            }
            // fall through
          case 57: break;
          case 12:
            { return symbol(TokenType.DIV);
            }
            // fall through
          case 58: break;
          case 13:
            { return symbol(TokenType.INT, Integer.parseInt(yytext()));
            }
            // fall through
          case 59: break;
          case 14:
            { return symbol(TokenType.COLON);
            }
            // fall through
          case 60: break;
          case 15:
            { return symbol(TokenType.SEMICOLON);
            }
            // fall through
          case 61: break;
          case 16:
            { return symbol(TokenType.LESS);
            }
            // fall through
          case 62: break;
          case 17:
            { return symbol(TokenType.ASSIGN);
            }
            // fall through
          case 63: break;
          case 18:
            { return symbol(TokenType.GREATER);
            }
            // fall through
          case 64: break;
          case 19:
            { return symbol(TokenType.ID, yytext());
            }
            // fall through
          case 65: break;
          case 20:
            { return symbol(TokenType.LEFTBRACKET);
            }
            // fall through
          case 66: break;
          case 21:
            { return symbol(TokenType.RIGHTBRACKET);
            }
            // fall through
          case 67: break;
          case 22:
            { return symbol(TokenType.LEFTCURLY);
            }
            // fall through
          case 68: break;
          case 23:
            { return symbol(TokenType.RIGHTCURLY);
            }
            // fall through
          case 69: break;
          case 24:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 70: break;
          case 25:
            { return symbol(TokenType.NEQ);
            }
            // fall through
          case 71: break;
          case 26:
            { return symbol(TokenType.AND);
            }
            // fall through
          case 72: break;
          case 27:
            { return symbol(TokenType.CHAR, yytext().substring(1,yytext().length()-1));
            }
            // fall through
          case 73: break;
          case 28:
            { yybegin(SINGLELINECOMMENT);
            }
            // fall through
          case 74: break;
          case 29:
            { return symbol(TokenType.FLOAT, Float.parseFloat(yytext()));
            }
            // fall through
          case 75: break;
          case 30:
            { return symbol(TokenType.DOUBLECOLON);
            }
            // fall through
          case 76: break;
          case 31:
            { return symbol(TokenType.EQ);
            }
            // fall through
          case 77: break;
          case 32:
            { return symbol(TokenType.IF);
            }
            // fall through
          case 78: break;
          case 33:
            { yybegin(MULTLINECOMMENT);
            }
            // fall through
          case 79: break;
          case 34:
            { return symbol(TokenType.IDINT);
            }
            // fall through
          case 80: break;
          case 35:
            { return symbol(TokenType.NEW);
            }
            // fall through
          case 81: break;
          case 36:
            { return symbol(TokenType.BOOL);
            }
            // fall through
          case 82: break;
          case 37:
            { return symbol(TokenType.IDCHAR);
            }
            // fall through
          case 83: break;
          case 38:
            { return symbol(TokenType.ELSE);
            }
            // fall through
          case 84: break;
          case 39:
            { return symbol(TokenType.NULL);
            }
            // fall through
          case 85: break;
          case 40:
            { return symbol(TokenType.READ);
            }
            // fall through
          case 86: break;
          case 41:
            { return symbol(TokenType.TRUE);
            }
            // fall through
          case 87: break;
          case 42:
            { return symbol(TokenType.IDFLOAT);
            }
            // fall through
          case 88: break;
          case 43:
            { return symbol(TokenType.FALSE);
            }
            // fall through
          case 89: break;
          case 44:
            { return symbol(TokenType.PRINT);
            }
            // fall through
          case 90: break;
          case 45:
            { return symbol(TokenType.RETURN);
            }
            // fall through
          case 91: break;
          case 46:
            { return symbol(TokenType.ITERATE);
            }
            // fall through
          case 92: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
